---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: redis
spec:
  host: redis.apps-crc.testing
  port:
    targetPort: 6379
  tls:
    termination: passthrough 
    insecureEdgeTerminationPolicy: None 
  to:
    kind: Service
    name: my-release-redis-master
